[package]
name = "scrubby"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
colored = "2.1.0"
md5 = "0.7.0"
mlua = { version = "0.9.6", features = ["lua54", "send", "serialize"] }
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
serenity = { version = "0.12.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "framework", "standard_framework", "cache"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
ureq = "2.9.6"
