# fly.toml app configuration file generated for scrubby on 2024-06-12T17:11:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scrubby'
primary_region = 'iad'


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  LUA_EXPOSE_ENV="SPOTIFY_SECRET"